export const NEW_CATEGORY_REQUEST = 'NEW_CATEGORY_REQUEST';
export const NEW_CATEGORY_SUCCESS = 'NEW_CATEGORY_SUCCESS';
export const NEW_CATEGORY_RESET = 'NEW_CATEGORY_RESET';
export const NEW_CATEGORY_FAIL = 'NEW_CATEGORY_FAIL';

export const CATEGORY_ALL_REQUEST = 'CATEGORY_ALL_REQUEST';
export const CATEGORY_ALL_SUCCESS = 'CATEGORY_ALL_SUCCESS';
export const CATEGORY_ALL_FAIL = 'CATEGORY_ALL_FAIL';

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_RESET = 'CATEGORY_DELETE_RESET';
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL';

export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST';
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS';
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
