export const ALL_RENT_REQUEST = 'ALL_RENT_REQUEST';
export const ALL_RENT_SUCCESS = 'ALL_RENT_SUCCESS';
export const ALL_RENT_FAIL = 'ALL_RENT_FAIL';

export const ALL_RENT_REQUEST_HOME = 'ALL_RENT_REQUEST_HOME';
export const ALL_RENT_SUCCESS_HOME = 'ALL_RENT_SUCCESS_HOME';
export const ALL_RENT_FAIL_HOME = 'ALL_RENT_FAIL_HOME';

export const RENT_DETAILS_REQUEST = 'RENT_DETAILS_REQUEST';
export const RENT_DETAILS_SUCCESS = 'RENT_DETAILS_SUCCESS';
export const RENT_DETAILS_FAIL = 'RENT_DETAILS_FAIL';

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET';
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL';

export const RENT_SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';

export const ADMIN_RENT_REQUEST = 'ADMIN_RENT_REQUEST';
export const ADMIN_RENT_SUCCESS = 'ADMIN_RENT_SUCCESS';
export const ADMIN_RENT_FAIL = 'ADMIN_RENT_FAIL';

export const UPDATE_RENT_REQUEST = 'UPDATE_RENT_REQUEST';
export const UPDATE_RENT_SUCCESS = 'UPDATE_RENT_SUCCESS';
export const UPDATE_RENT_RESET = 'UPDATE_RENT_RESET';
export const UPDATE_RENT_FAIL = 'UPDATE_RENT_FAIL';

export const DELETE_RENT_REQUEST = 'DELETE_RENT_REQUEST';
export const DELETE_RENT_SUCCESS = 'DELETE_RENT_SUCCESS';
export const DELETE_RENT_RESET = 'DELETE_RENT_RESET';
export const DELETE_RENT_FAIL = 'DELETE_RENT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
